language: php

php:
  - 7.0

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

before:
  - cp .env.example .env  # Create a new .env file
  - php artisan key:generate # Generate application key

script: vendor/bin/phpunit